# Generated by Django 2.0.3 on 2018-03-29 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20180329_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField()),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdBotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('step', models.IntegerField()),
                ('volume', models.IntegerField(null=True)),
                ('switch', models.BooleanField(default=False)),
                ('frequency', models.DurationField()),
                ('payment_method', models.CharField(max_length=32)),
                ('ad_id', models.IntegerField()),
                ('api_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyModel')),
            ],
        ),
    ]
