# Generated by Django 2.0.3 on 2018-04-03 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField()),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('step', models.IntegerField()),
                ('volume', models.IntegerField(null=True)),
                ('switch', models.BooleanField(default=False)),
                ('frequency', models.DurationField()),
                ('payment_method', models.CharField(choices=[('qiwi', 'QIWI'), ('cash-deposit', 'CASH_DEPOSIT'), ('transfers-with-specific-bank', 'SPECIFIC_BANK')], max_length=64)),
                ('trade_direction', models.CharField(choices=[('buy-bitcoins-online', 'ONLINE_SELL'), ('sell-bitocins-online', 'ONLINE_BUY')], max_length=64)),
                ('ad_id', models.IntegerField()),
                ('change_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
