# Generated by Django 2.0.3 on 2018-04-03 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_bot', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adbot',
            name='api_keys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKey'),
        ),
        migrations.AddField(
            model_name='adbot',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='bot_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_bot.AdBot'),
        ),
    ]
