# Generated by Django 2.0.3 on 2018-03-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbotmodel',
            name='trade_direction',
            field=models.CharField(choices=[('sell-bitcoins-online', 'Встать на покупку'), ('buy-bitcoins-online', 'Встать на продажу')], max_length=32),
            preserve_default=False,
        ),
    ]
