# Generated by Django 2.0.3 on 2018-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0003_auto_20180404_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='ad_id',
            field=models.IntegerField(unique=True),
        ),
    ]
