# Generated by Django 2.0.3 on 2018-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0004_auto_20180405_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adbot',
            old_name='volume',
            new_name='volume_max',
        ),
        migrations.AddField(
            model_name='adbot',
            name='volume_min',
            field=models.IntegerField(null=True),
        ),
    ]
