# Generated by Django 2.0.3 on 2018-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0005_auto_20180405_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbot',
            name='change_time',
        ),
        migrations.AddField(
            model_name='adbot',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
