# Generated by Django 2.0.3 on 2018-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0006_auto_20180407_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='request_url',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='response_data',
        ),
    ]
