# Generated by Django 2.0.3 on 2018-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0007_auto_20180407_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='stop_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена для остановки', max_digits=9),
        ),
    ]
