# Generated by Django 2.0.3 on 2018-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0008_auto_20180407_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='frequency',
            field=models.DurationField(help_text='Частота обновления'),
        ),
        migrations.AlterField(
            model_name='adbot',
            name='step',
            field=models.IntegerField(help_text='Шаг обновления цены'),
        ),
        migrations.AlterField(
            model_name='adbot',
            name='volume_max',
            field=models.IntegerField(help_text='Фильтр по мелким игрокам', null=True),
        ),
        migrations.AlterField(
            model_name='adbot',
            name='volume_min',
            field=models.IntegerField(help_text='Фильтр по крупным игрокам', null=True),
        ),
    ]
