# Generated by Django 2.0.3 on 2018-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0009_auto_20180407_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbot',
            name='price_round',
            field=models.BooleanField(default=True),
        ),
    ]
