# Generated by Django 2.0.3 on 2018-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0010_adbot_price_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbot',
            name='executing',
            field=models.BooleanField(default=False),
        ),
    ]
