# Generated by Django 2.0.3 on 2018-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0011_adbot_executing'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbot',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
