# Generated by Django 2.0.3 on 2018-06-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0012_adbot_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='bot_model',
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
