# Generated by Django 2.0.3 on 2018-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0014_auto_20180611_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
