# Generated by Django 2.0.3 on 2018-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0015_opentrades_delete_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='open_trades',
            field=models.ManyToManyField(blank=True, to='ad_bot.OpenTrades'),
        ),
    ]
