# Generated by Django 2.0.3 on 2018-06-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0016_auto_20180611_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbot',
            name='open_trades',
        ),
    ]
