# Generated by Django 2.0.3 on 2018-06-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0017_remove_adbot_open_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='adbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_bot.AdBot'),
            preserve_default=False,
        ),
    ]
