# Generated by Django 2.0.3 on 2018-06-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0018_opentrades_adbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opentrades',
            name='delete_flag',
        ),
    ]
