# Generated by Django 2.0.3 on 2018-06-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0019_remove_opentrades_delete_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number', models.IntegerField(blank=True)),
                ('contact_id', models.IntegerField()),
                ('agent', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=9)),
                ('fee_btc', models.DecimalField(decimal_places=8, max_digits=9)),
                ('adbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_bot.AdBot')),
            ],
        ),
    ]
