# Generated by Django 2.0.3 on 2018-06-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0020_reportdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
