# Generated by Django 2.0.3 on 2018-06-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0021_auto_20180614_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='number',
        ),
    ]
