# Generated by Django 2.0.3 on 2018-06-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0022_remove_reportdata_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBotTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('executing', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='adbot',
            name='executed_at',
        ),
        migrations.RemoveField(
            model_name='adbot',
            name='executing',
        ),
        migrations.AddField(
            model_name='adbottechnical',
            name='adbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_bot.AdBot'),
        ),
    ]
