# Generated by Django 2.1b1 on 2018-06-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0023_auto_20180615_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbottechnical',
            name='executing',
        ),
    ]
