# Generated by Django 2.1b1 on 2018-06-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0024_remove_adbottechnical_executing'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbottechnical',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
