# Generated by Django 2.1b1 on 2018-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0025_adbottechnical_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbottechnical',
            name='message_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adbottechnical',
            name='message_frequency',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adbottechnical',
            name='message_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
