# Generated by Django 2.1b1 on 2018-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0027_auto_20180624_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbottechnical',
            name='message_task_id',
        ),
        migrations.RemoveField(
            model_name='adbottechnical',
            name='task_id',
        ),
        migrations.AddField(
            model_name='adbottechnical',
            name='executing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adbottechnical',
            name='message_executing',
            field=models.BooleanField(default=False),
        ),
    ]
