# Generated by Django 2.1b1 on 2018-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0030_auto_20180625_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbottechnical',
            name='adbot',
        ),
        migrations.DeleteModel(
            name='AdBotTechnical',
        ),
    ]
