# Generated by Django 2.1b1 on 2018-06-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0031_auto_20180625_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBotTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('executing', models.BooleanField(default=False)),
                ('message_executing', models.BooleanField(default=False)),
                ('message_executed_at', models.DateTimeField(blank=True, null=True)),
                ('message_frequency', models.DurationField(blank=True, default='30', null=True)),
                ('adbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_bot.AdBot')),
            ],
        ),
    ]
