# Generated by Django 2.1b1 on 2018-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0032_adbottechnical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='payment_method',
            field=models.CharField(choices=[('qiwi', 'QIWI'), ('cash-deposit', 'CASH_DEPOSIT'), ('transfers-with-specific-bank', 'SPECIFIC_BANK'), ('yandex-money', 'YANDEX_MONEY')], max_length=64),
        ),
    ]
