# Generated by Django 2.1b1 on 2018-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_bot', '0033_auto_20180705_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbot',
            name='payment_method',
            field=models.CharField(choices=[('qiwi', 'QIWI'), ('cash-deposit', 'CASH_DEPOSIT'), ('transfers-with-specific-bank', 'SPECIFIC_BANK'), ('yandex-money', 'YANDEXMONEY')], max_length=64),
        ),
    ]
